# Generated by Django 2.0.3 on 2018-04-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional comments about this pick.'),
        ),
    ]
