# Generated by Django 2.0.1 on 2018-01-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['start_date']},
        ),
    ]
