# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='harvest_date',
            field=models.DateField(default='2017-10-01'),
            preserve_default=False,
        ),
    ]
