# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardenhub', '0002_harvest_harvest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='owners',
        ),
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garden',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garden',
            name='gardeners',
            field=models.ManyToManyField(related_name='_garden_gardeners_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='garden',
            name='managers',
            field=models.ManyToManyField(related_name='_garden_managers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plot',
            name='crops',
            field=models.ManyToManyField(to='gardenhub.Crop'),
        ),
        migrations.AddField(
            model_name='plot',
            name='gardener',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
