# Generated by Django 2.0.3 on 2018-04-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0002_pick_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='map_image',
            field=models.ImageField(blank=True, help_text='A map of this garden.', upload_to='maps'),
        ),
    ]
