# Generated by Django 2.0 on 2017-12-06 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0002_auto_20171205_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='_affiliation_managers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='garden',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='_garden_managers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plot',
            name='gardeners',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
