# Generated by Django 2.0.1 on 2018-01-12 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0002_auto_20180111_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='canceled_date',
        ),
        migrations.AddField(
            model_name='order',
            name='canceled_timestamp',
            field=models.DateTimeField(blank=True, help_text='The moment this order was canceled, if so.', null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='People who can edit this affiliation.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='title',
            field=models.CharField(help_text='The name of this affiliation.', max_length=255),
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(help_text='Photo of this crop.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='crop',
            name='title',
            field=models.CharField(help_text='All lowercase name of this crop.', max_length=255),
        ),
        migrations.AlterField(
            model_name='garden',
            name='address',
            field=models.CharField(help_text='The full, neatly-formatted mailing address of this garden.', max_length=255),
        ),
        migrations.AlterField(
            model_name='garden',
            name='affiliations',
            field=models.ManyToManyField(blank=True, help_text="This garden's affiliations.", related_name='gardens', to='gardenhub.Affiliation'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='People who can edit this garden, edit plots on this garden, and view/place orders for plots on this garden.', related_name='gardens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='garden',
            name='photo',
            field=models.ImageField(blank=True, help_text='A photo of this garden.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='garden',
            name='pickers',
            field=models.ManyToManyField(blank=True, help_text='People who are assigned to fulfill orders on this garden.', related_name='_garden_pickers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='canceled',
            field=models.BooleanField(default=False, help_text='Whether or not this order has been canceled.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='crops',
            field=models.ManyToManyField(help_text='Crops that should be picked for this order.', to='gardenhub.Crop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(help_text='The day picking should end for this order.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='plot',
            field=models.ForeignKey(help_text='The plot this order targets for picking.', on_delete=django.db.models.deletion.DO_NOTHING, to='gardenhub.Plot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requester',
            field=models.ForeignKey(help_text='Person who submitted this order.', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(help_text='The day picking should begin for this order.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The exact moment this order was submitted.'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='crops',
            field=models.ManyToManyField(help_text='Crops that were harvested by this pick.', to='gardenhub.Crop'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='picker',
            field=models.ForeignKey(help_text='Person who submitted this pick.', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pick',
            name='plot',
            field=models.ForeignKey(help_text='Plot this pick occurred upon.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='picks', to='gardenhub.Plot'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The exact moment this pick was submitted.'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='garden',
            field=models.ForeignKey(help_text='The garden this plot is a part of.', on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='gardenhub.Garden'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='gardeners',
            field=models.ManyToManyField(blank=True, help_text='People who grow food on this plot. Listing them here enables them to place orders.', related_name='plots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, help_text="A temporary token used to activate the user's account upon being invited to the site initially.", max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The exact moment this user joined the website.', verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="The user's email address, which is used for notifications and doubles as the username for logging in.", max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text="The user's given name or nickname, sometimes used in a casual context.", max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text="The user's family name, sometimes used to distinguish one user from another.", max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='A photo of the user or an avatar.', upload_to='', verbose_name='photo'),
        ),
    ]
