# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardenhub', '0003_auto_20171001_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('canceled_date', models.DateField(blank=True, null=True)),
                ('crops', models.ManyToManyField(to='gardenhub.Crop')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenhub.Plot')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='garden',
            name='gardeners',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='crops',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='plot',
        ),
        migrations.AddField(
            model_name='harvest',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harvest',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('finished', 'Finished')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
