# Generated by Django 2.0.1 on 2018-01-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0003_auto_20180112_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional comments about this order.'),
        ),
    ]
