# Generated by Django 2.0 on 2017-12-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0003_auto_20171206_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='crops',
            field=models.ManyToManyField(blank=True, to='gardenhub.Crop'),
        ),
    ]
