# Generated by Django 2.0 on 2017-12-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0004_auto_20171206_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='photo'),
        ),
    ]
