# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardenhub', '0005_auto_20171108_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('managers', models.ManyToManyField(related_name='_organization_managers_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='garden',
            name='affiliation',
            field=models.ManyToManyField(to='gardenhub.Organization'),
        ),
    ]
