# Generated by Django 2.0.1 on 2018-01-22 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0005_auto_20180121_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plot',
            field=models.ForeignKey(help_text='The plot this order targets for picking.', on_delete=django.db.models.deletion.PROTECT, to='gardenhub.Plot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requester',
            field=models.ForeignKey(help_text='Person who submitted this order.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pick',
            name='picker',
            field=models.ForeignKey(help_text='Person who submitted this pick.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pick',
            name='plot',
            field=models.ForeignKey(help_text='Plot this pick occurred upon.', on_delete=django.db.models.deletion.PROTECT, related_name='picks', to='gardenhub.Plot'),
        ),
    ]
