# Generated by Django 2.0 on 2017-12-10 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0005_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='gardenhub.Garden'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='title',
            field=models.CharField(help_text="The plot's name is probably a number, like 11. The plot should be clearly labeled with a sign.", max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
