# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0006_auto_20171109_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='affiliation',
            field=models.ManyToManyField(related_name='_garden_affiliation_+', to='gardenhub.Organization'),
        ),
    ]
