# Generated by Django 2.0 on 2017-12-10 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0006_auto_20171209_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='managers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='garden',
            name='affiliations',
            field=models.ManyToManyField(blank=True, related_name='gardens', to='gardenhub.Affiliation'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='gardens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plot',
            name='crops',
            field=models.ManyToManyField(blank=True, related_name='_plot_crops_+', to='gardenhub.Crop'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='gardeners',
            field=models.ManyToManyField(blank=True, related_name='plots', to=settings.AUTH_USER_MODEL),
        ),
    ]
