# Generated by Django 2.0.1 on 2018-02-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0006_auto_20180122_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(help_text='Photo of this crop.', upload_to='crops'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='photo',
            field=models.ImageField(blank=True, help_text='A photo of this garden.', upload_to='gardens'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='A photo of the user or an avatar.', upload_to='users', verbose_name='photo'),
        ),
    ]
