# Generated by Django 2.0.1 on 2018-02-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0007_auto_20180201_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='title',
            field=models.CharField(help_text='All lowercase name of this crop.', max_length=255, unique=True),
        ),
    ]
