# Generated by Django 2.0 on 2017-12-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0007_auto_20171210_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
