# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardenhub', '0008_order_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('managers', models.ManyToManyField(related_name='_affiliation_managers_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='affiliation',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AddField(
            model_name='garden',
            name='affiliations',
            field=models.ManyToManyField(related_name='_garden_affiliations_+', to='gardenhub.Affiliation'),
        ),
    ]
