# Generated by Django 2.0 on 2017-12-13 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0008_garden_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='pickers',
            field=models.ManyToManyField(related_name='_garden_pickers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
