# Generated by Django 2.0.1 on 2018-02-01 20:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0008_auto_20180201_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="The user's phone number, so site admins can directly contact them if needed.", max_length=128),
        ),
    ]
