# Generated by Django 2.0 on 2017-12-14 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0009_garden_pickers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='pickers',
            field=models.ManyToManyField(blank=True, related_name='_garden_pickers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
