# Generated by Django 2.0 on 2017-12-06 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0009_auto_20171201_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gardenhub.Plot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
