# Generated by Django 2.0 on 2017-12-20 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0010_auto_20171214_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvest',
            old_name='employee',
            new_name='picker',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='harvest_date',
        ),
        migrations.AddField(
            model_name='harvest',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='harvest',
            name='plot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='picks', to='gardenhub.Plot'),
            preserve_default=False,
        ),
    ]
