# Generated by Django 2.0 on 2017-12-20 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardenhub', '0011_auto_20171219_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('picker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='picks', to='gardenhub.Plot')),
            ],
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='picker',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='plot',
        ),
        migrations.DeleteModel(
            name='Harvest',
        ),
    ]
