crops_list = [
    'acorn squash',
    'alfalfa spouts',
    'amaranth',
    'apricots',
    'artichoke',
    'asparagus',
    'avocado',
    'bananas',
    'barley',
    'basil',
    'bay leaf',
    'bean sprouts',
    'beets',
    'blackberries',
    'blueberries',
    'bok choy',
    'broccoli',
    'brussels sprouts',
    'butternut squash',
    'cabbage',
    'caper',
    'carrots',
    'cauliflower',
    'cayenne peppers',
    'celery',
    'chamomile',
    'cherries',
    'cherry tomatoes',
    'chestnuts',
    'chickpeas',
    'chives',
    'cilantro',
    'collard greens',
    'coriander',
    'corn',
    'cranberries',
    'cucumber',
    'daisy',
    'daylily',
    'dill',
    'eggplant',
    'elderberries',
    'fennel',
    'garlic',
    'ginger',
    'gourds',
    'grapefruit',
    'green apples',
    'green beans',
    'green grapes',
    'green pepper',
    'habanero pepper',
    'honeydew',
    'hops',
    'hot peppers',
    'huckleberries',
    'jalapeno peppers',
    'kale',
    'kiwi',
    'kohlrabi',
    'leeks',
    'lentils',
    'lettuce',
    'luffa',
    'marigold',
    'mustard',
    'okra',
    'olives',
    'onion',
    'oranges',
    'oregano',
    'oyster mushrooms',
    'parsley',
    'peach',
    'peanuts',
    'pears',
    'peas',
    'peppermint',
    'pineapple',
    'portobello mushrooms',
    'potatoes',
    'pumpkin',
    'purple grapes',
    'quinoa',
    'radish',
    'raspberries',
    'red apple',
    'red lettuce',
    'red onions',
    'red pepper',
    'rosemary',
    'sage',
    'scallions',
    'sesame',
    'shallots',
    'shitake mushrooms',
    'snap peas',
    'snow peas',
    'soy beans',
    'spinach',
    'starfruit',
    'strawberries',
    'sunflower',
    'sweet corn',
    'sweet potatoes',
    'thai basil',
    'thyme',
    'tomatillo',
    'tomatoes',
    'truffle',
    'tulips',
    'walnuts',
    'watermelon',
    'white onion',
    'yams',
    'yellow onion',
    'yellow peppers',
    'zucchini'
]
